import { Inter } from "next/font/google";
import "./globals.css";
import ToastProvider from "@/components/ToastProvider/ToastProvider";
import Footer from "@/layouts/Footer/Footer";
import Header from "@/layouts/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <ToastProvider />
        {children}
        <Footer />
      </body>
    </html>
  );
}
